resources:
- name: concourse-demo
  type: git
  source:
    uri: http://github.com/karafelix/concourse-demo.git
    branch: master

- name: text-file
  type: s3
  source:
    bucket: stemcells
    regexp: text-file
    access_key_id: {{SWIFT_USERNAME}}
    secret_access_key: {{SL_API_KEY}}
    region_name: {{SWIFT_CLUSTER}}
    endpoint: {{SL_ENDPOINT}}

jobs:
- name: hello-world
  plan:
  - get: concourse-demo
    trigger: true
  - task: say-hello
    file: concourse-demo/ci/tasks/hello.yml
  - put: text-file
    params: {from: out/text-file}

- name: goodbye
  plan:
  - get: concourse-demo
    trigger: true
  - get: text-file
    trigger: true
    passed: [hello-world]
  - task: goodbye
    file: concourse-demo/ci/tasks/goodbye.yml
    config:
      params:
        NAME: Abacus
